### ISSUE TITLE
Connect the Dots and Azure Stream Analytics... How to?

### ISSUE THREAD

**Issue by mpilant** [MSOpenTech/connectthedots#167]
I think I must be missing something obvious.  I have CTD up and running, sending lots of nice data to the event hub, website displaying data fine..  However, while there are several statements indicating running Azure Stream Analytics is "easy" I have yet to be able to get it (or see it) running.

It seems I may need to define AZURESTREAMANALYTICS... somewhere, but there is *no* documentation saying just what has to be done.

Very frustrating.
- Mark

**Comment by spyrossak** [comment]
What the...
There used to be a SA_setup.md file in the /StreamAnalyticsQueries folder. Found it, pushed. Now I just have to find where it should be linked from in the readme.md.
Sorry, and thanks for pointing out!
Spyros

**Comment by spyrossak** [comment]
Added link into readme.md for Stream Analytics setup.

**Comment by mpilant** [comment]
Well, I tried following the SA_setup, and something still isn't right.

First, it appears the instructions in SA_setup are for a somewhat older Azure portal than the current one.  (This is the "manage" portal, not the new preview portal.)  Things like "Alias" names are needed, StreamingAnalytics policy name, etc.

Second, I don't get any alerts posted to the website.  Which may or may not be because of SA.  If I block the light sensor, I can see the output drop in the graph, but there isn't an alert generated.

Finally, the "Alerts" and "LightSecsor" jobs have a "Processing" status, while the "Aggregates" job has a "Degraded" status.

Very confused.

- Mark

**Comment by spyrossak** [comment]
You are right on two specific counts: the instructions are for (a) the original Azure "manage"  portal, and (b) for a slightly earlier version of ConnectTheDots. I just grabbed what I found without editing. Will do so as soon as I can.

The reason the instructions were not there, it turns out, is that the most recent version of AzurePrep automatically creates the SA jobs for you, so the instructions are mostly redundant, and only if you want to do it yourself. Need to be edited in that regard.

Now why the alerts are not posting, that is another matter. Would need to check all the settings. Basically, if the data is in ehdevices, and the SA Input, Query, and Output are as defined, the alerts *should* show up in the website. The only thing I can suggest is that you check the "Operations Logs" on each Event Hub page to see if you can identify the source of the problem.

**Comment by mpilant** [comment]
> The reason the instructions were not there, it turns out, is that the most recent version of AzurePrep automatically creates the SA jobs for you

This would suggest having some form of update history or release notes (with history) would be beneficial.  Otherwise, the novice will get caught by not knowing whether the problem(s) being encountered are of their own doing or are some form of mismatch with the instructions / infrastructure.  This would almost certainly be a turn-off to going forward.

I have checked the operation logs for both event hubs, and the only entries are weeks old for the "CreateConsumerGroup" when I first created everything.  There is noting since May 13, and I have been trying to get SA going for the past several days, so that would indicate there hasn't been anything posted related to SA; or the device for that matter.

I would seem it would be more productive to toss everything I have and start over with the latest. :-(

- Mark
