### ISSUE TITLE
Errors in deploying to Intel Galileo

### ISSUE THREAD

**Issue by Pooja-B** [MSOpenTech/connectthedots#41]
I tried to deploy the sample application given for Intel Galileo but it is giving runtime errors. Has someone worked with Galileo?
I am getting the following errors

'ConnectTheDotsGalileo.exe' (Win32): Loaded 'C:\test\ConnectTheDotsGalileo.exe'. Symbols loaded.
'ConnectTheDotsGalileo.exe' (Win32): Loaded 'C:\Windows\System32\ntdll.dll'. Cannot find or open the PDB file.
'ConnectTheDotsGalileo.exe' (Win32): Loaded 'C:\Windows\System32\kernel32.dll'. Cannot find or open the PDB file.
'ConnectTheDotsGalileo.exe' (Win32): Loaded 'C:\Windows\System32\kernel32legacy.dll'. Cannot find or open the PDB file.
'ConnectTheDotsGalileo.exe' (Win32): Loaded 'C:\Windows\System32\KernelBase.dll'. Cannot find or open the PDB file.
The program '[1924] ConnectTheDotsGalileo.exe' has exited with code -1073741515 (0xc0000135) 'A dependent dll was not found'.

**Comment by toolboc** [comment]
@Pooja-B, not having issues over here, although I wonder if this wasn't addressed in the pending pull requests.  In the meantime, can you try the Galileo code that is available in @ivanignatiev  's [fork](https://github.com/ivanignatiev/connectthedots)?

**Comment by Pooja-B** [comment]
Can you please suggest me the proper steps to deploy the solution to Galileo?

**Comment by toolboc** [comment]
See the documentation available in my [pending pull request](https://github.com/toolboc/connectthedots/blob/master/Devices/IntelGalileo/ConnectTheDotsGalileo/Docs/Intel%20Galileo%20setup.md) for detailed instructions on deploying to the Galileo.  Again, I want to stress that you use the updated Galileo project available in @ivanignatiev 's [fork](https://github.com/ivanignatiev/connectthedots).

**Comment by Pooja-B** [comment]
Thanks I will try that .

**Comment by ivanignatiev** [comment]
@Pooja-B, it's happens because in the current branch /ConnectTheDotsGalileo.vcxproj.user file is missing and Visual Studio doesn't copy DLLs to the working directory on Intel Galileo board. 

It'll work fine when my pull request will be accepted. 

Fix for the current version in master branch: 
Make sure that your Remote Windows Debugger is well configured, `Additional Files to Deploy` should contain `$(ProjectDir)\ConnectTheDotsGalileo.exe.config;$(SolutionDir)\lib\libeay32.dll;$(SolutionDir)\lib\ssleay32.dll;$(SolutionDir)\lib\qpid-proton.dll;`

![remote windows debugger](https://cloud.githubusercontent.com/assets/1072103/6233449/2d479954-b6d3-11e4-8255-11d2bde1509c.png)

**Comment by Pooja-B** [comment]
Thanks, It is working fine now. I was struggling from many days to implement the " I " part of my IoT app, Thanks for a great example and the documentation part is also well written.  :)
