### ISSUE TITLE
Suggestion: Script to clean up Azure resources from CTD

### ISSUE THREAD

**Issue by devhammer** [MSOpenTech/connectthedots#63]
I've run the ConnectTheDots demo app a couple of times now, once for a user group, and again for an online conference.

While it's a great demo for showing end-to-end IoT communication, there's a lot involved in cleaning up the Azure resources used by the demo, and it would be great if this could be automated to some degree.
Perhaps it would be possible to have the app that performs a substantial portion of the setup also create a powershell script that could use the Azure command line APIs to remove the Service Bus and Storage resources it creates.

If I can find the time to go through the code and try my hand at hacking it together, and if I manage to make something that works, I'll submit it as a pull request.

**Comment by dinarisio** [comment]
Going to start at ehconsole branch.

**Comment by dinarisio** [comment]
Draft at ehconsoleUpd branch.

**Comment by dinarisio** [comment]
Merged with master. Instead of creating script that could be started accidentally and delete everything, there is a tool that asks for your initial namespace name (could just choose from a list) and confims deletion of instances that could be related (according to deploy scenarios). Comments are welcome.
